import './globals.css';
import { fetchAPI } from '@/lib/api';
import { getStrapiMedia } from '@/lib/media';
import { headerQuery } from '@/queries/populate';
import Header from './Header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await fetchAPI('/header', headerQuery);

  const { menu, showLogo, Logo: logo, socialLinks } = data.data.attributes;
  const logoUrl = getStrapiMedia(logo.image);

  return (
    <html lang='en'>
      <body>
        <Header
          logoUrl={logoUrl}
          alt={logo.alt}
          showLogo={showLogo}
          socialLinks={socialLinks}
          menu={menu}
        />
        {children}
      </body>
    </html>
  );
}
