import './globals.css';
import { fetchAPI } from '@/lib/api';
import { getStrapiMedia } from '@/lib/media';
import { footerQuery, headerQuery } from '@/queries/populate';
import Header from './Header';
import Footer from './Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [headerData, footerData] = await Promise.all([
    fetchAPI('/header', headerQuery),
    fetchAPI('/brand-info', footerQuery),
  ]);

  const {
    menu,
    showLogo,
    Logo: logo,
    socialLinks: headerSocialLinks,
  } = headerData.data.attributes;
  const logoUrl = getStrapiMedia(logo.image);

  const {
    brandEmail,
    brandName,
    socialLinks: footerSocialLinks,
  } = footerData.data.attributes;

  return (
    <html lang='en'>
      <body>
        <Header
          logoUrl={logoUrl}
          alt={logo.alt}
          showLogo={showLogo}
          socialLinks={headerSocialLinks}
          menu={menu}
        />
        {children}

        <Footer
          brandEmail={brandEmail}
          brandName={brandName}
          socialLinks={footerSocialLinks}
        />
      </body>
    </html>
  );
}
